### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by sypark990** [sanketkshah/NeurADP-for-Ride-Pooling#2]
Hello, I'm Seongyeon Park

I found this paper very interesting and I wanna see how it works using this code.
But It seems there is no available data in this repo.
So I wanna ask you that you can share the data needed to run this code. 

Thank you.

**Comment by sanketkshah** [comment]
Hello, This seems to be the same as issue #1. Please send me an email, and I'll be happy to forward you the data!
